### ISSUE TITLE
Stworzenie nowego repozytorium

### ISSUE THREAD

**Issue by jdabrowski5701** [JanuaryDecember/Team-Project-PB#1]
Celem zadania jest stworzenie nowego repozytorium na platformie GitHub

**Comment by jdabrowski5701** [comment]
Zadanie wykonane

**Comment by JanuaryDecember** [comment]
Dokumentacja w załączniku.
[Dokumentacja#1.pdf](https://github.com/JanuaryDecember/Team-Project-PB/files/15083477/Dokumentacja.1.pdf)

**Comment by jzaprzalka** [comment]
Zadnie wykonane: 5
