### ISSUE TITLE
Modyfikacja zapisu paragonów na Google Drive

### ISSUE THREAD

**Issue by Aikoocioq** [JanuaryDecember/Team-Project-PB#10]
Zadanie polega na zmianie sposobu zapisu paragonów. Zamiast zapisywać je "luzem" na Google Drive, powinny one trafiać do folderu danego użytkownika.

**Comment by czyzia2002** [comment]
Zmodyfikowano sposób dodawania zdjęcia paragonów na Google Drive.
W chwili obecnej, każdy użytkownik ma swój folder, którego nazwa jest tworzona na podstawie id użytkownika z bazy danych i w nim przechowywane są wszystkie zdjęcia przesłane przez użytkownika.

Pobieranie id obecnie zalogowanego użytkownika.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/3c216583-5914-48af-96c7-2f9f9e3c4b88)

Sprawdzenie czy użytkownik ma już folder na dysku, jeśli nie tworzenie.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/fdb148b1-bd3a-4f79-a29a-9696716e2f68)


W celu tworzenia nowego folderu zaimplementowano metodę "CreateUserFolder"

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/62c4f3b9-8951-4824-844b-17649dfe2fd2)

a w celu sprawdzania czy użytkownik, już wcześniej dodawał zdjęcia na dysk i ma już swój folder, metoda "FindUserFolder", która zwraca id istniejącego już folderu, bądź null jeśli taki folder nie istnieje.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/1eeaf899-69cf-42c6-b4f6-a0a6c9ca15ed)

Screeny z dysku z utworzonymi folderami i przesłanymi zdjęciami.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/7fbd38db-e621-492c-add1-39937425f888)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/9e5010a4-a1a9-4aa5-a5c4-eabc96cb84af)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/6ea45e26-7ce4-4be7-9c75-63fc9923d480)
