### ISSUE TITLE
Wprowadzenie wykresu wydatków portfela

### ISSUE THREAD

**Issue by Aikoocioq** [JanuaryDecember/Team-Project-PB#11]
Zadanie polega na dodaniu kolejnego wykresu na stronie portfela, zawierającego zestawienie wydatków na podstawie kategorii. Dodatkowym zadaniem jest również zbadanie kwestii niedziałającej legendy w jednym z wykresów na stronie głównej.

**Comment by Ewad20** [comment]
Dodano komponent _ExpensesChart_ wykorzystujący _chart.js_ do generowania wykresu wydatków z transakcji. Komponent przyjmuje trzy właściwości: _transactions, categories_ i _findCategoryName_. Wykorzystuje hooki _useRef_ i _useEffect_ do zarządzania instancją wykresu. Transakcje filtruje się według typu "expenditure", grupuje i przekształca do postaci odpowiedniej do wykorzystania w wykresie. Następnie tworzony jest nowy wykres za pomocą referencji do elementu _canvas_.
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/119815824/35294736-47bc-47f6-87f8-449bb1f12615)

Instancja wykresu jest tworzona przy użyciu danych _labels_ i _data_, ustawionych w formie opisu _doughnut_ (pierścienia). Kolorystyka tła i obramowania są predefiniowane dla każdej sekcji wykresu.
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/119815824/b7d50a2c-62e7-4819-a788-fbc97fcbe58e)

Komponent _ExpensesChart_ zawiera też funkcję zwrotną, która niszczy instancję wykresu podczas oczyszczania komponentu, oraz funkcję do grupowania transakcji według kategorii. Zwraca element _canvas_ do renderowania wykresu oraz odpowiednie style.
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/119815824/256b8e00-013c-4a4d-959a-9aeadc14b96a)

Zaimplementowano sekcję prezentującą dwa rodzaje wykresów. Pierwszy wykres, o nazwie _ExpensesChart_, wyświetlany jest w lewej kolumnie i przedstawia wydatki zgrupowane według kategorii. Drugi wykres, _TransactionsChart_, umieszczony w prawej kolumnie, pokazuje stosunek przychodów do wydatków. Poniżej tego wykresu prezentowana jest pozostała kwota dostępna w danym portfelu.
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/119815824/9da666e8-3804-4615-bd87-62f67009635e)

Wygląd wykresów na stronie:
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/119815824/3d21dcf8-170c-481b-a0e5-d673c27c35c8)
