### ISSUE TITLE
Wyświetlanie zdjęcia profilowego

### ISSUE THREAD

**Issue by Aikoocioq** [JanuaryDecember/Team-Project-PB#12]
Zadanie polega na dodaniu wyświetlania zdjęcia profilowego na pasku nawigacyjnym, zaraz obok przycisku przenoszącego na profil. Dodatkowym elementem zadania jest też podmiana treści przycisku z "Profile" na imię użytkownika oraz drobna zmiana sposobu wyświetlania opcji dodawania zdjęcia do profilu - zmiana kolejności przycisków i przeniesienie ich z wyświetlania profilu do edycji profilu.

**Comment by kasiagrygo** [comment]
Wyświetlanie zdjęcia profilowego
Zamiast „Profile” wyświetla nam się imię użytkownika oraz obok miniaturka zdjęcia profilowego.  
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/131908455/1bb858eb-8a46-4247-a4b3-4fb29ce7a1c4)

W przypadku braku dodanego zdjęcie mamy okienko z automatycznym zdjęciem.
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/131908455/f58a793a-e880-4b7a-a8d8-e6dbc2a0a427)

Funkcja renderProfile wyświetla zdjęcie profilowe użytkownika, jeśli użytkownik nie posiada własnego zdjęcia, wyświetlana jest domyślna ikona profilu. 
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/131908455/e72a5c1c-2e71-4941-8091-8c595a2ef2be)

Dodawanie zdjęcia profilowego zostało przeniesione do formularza edycji danych.
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/131908455/a9eaacb5-de83-4282-8211-985741fb0d95)
