### ISSUE TITLE
Drobne naprawy

### ISSUE THREAD

**Issue by Aikoocioq** [JanuaryDecember/Team-Project-PB#13]
Zadanie polega na naprawieniu kilku błędów, znalezionych w aplikacji:
- Odnalezienie miejsca w kodzie, gdzie automatycznie tworzone są kategorie NewCategory1, NewCategory2 i NewCategory3. Należy usunąć ich tworzenie, jako iż są sprzeczne z zamysłem kategorii domyślnych, a w dodatku niepotrzebne.
- Naprawienie wyświetlania nazwy użytkownika na stronie głównej.
- Naprawienie wyświetlania nazwy portfela po jego wybraniu z listy.

**Comment by jdabrowski5701** [comment]
1. Odnalezienie miejsca w kodzie, gdzie automatycznie tworzone są kategorie NewCategory1, NewCategory2 i NewCategory3. Należy usunąć ich tworzenie, jako iż są sprzeczne z zamysłem kategorii domyślnych, a w dodatku niepotrzebne.

Znaleziono fragment odpowiedzialny za tworzenie kategorii i usunięcie go. Wymagana jest migracja i aktualizacja bazy danych w celu naniesienia poprawek.

![obraz_2024-04-30_123456903](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/97f24841-3af5-460c-974e-e795bbeaf7b6)

![obraz_2024-04-30_123537948](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/87ca3b81-bbe1-4923-bfcc-232e88bc7162)

2. Naprawienie wyświetlania nazwy użytkownika na stronie głównej.

Znaleziono brak fragmentu kodu i naprawiono błąd, który wynikał z braku parsowania pliku JSON.

![obraz_2024-04-30_130355040](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/a6d62050-801e-46ea-921a-e63da972eda2)

![obraz_2024-04-30_130506079](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/15e9d250-0806-485b-b15e-3b4a0493218e)

3. Naprawienie wyświetlania nazwy portfela po jego wybraniu z listy.

Dodanie pobierania nazwy portfela oraz wyświetlania go zamiast identyfikatora.

![obraz_2024-04-30_131513047](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/39da1991-55fe-4d5c-99f5-33048055cd53)

![obraz_2024-04-30_131622897](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/706bda74-3720-4e05-b200-a4dc06e0c0d0)


Podsumowanie:
Wszystkie zadania zostały wykonane i występujące wcześniej błędy zostały naprawione.
