### ISSUE TITLE
Aktualizacja strony z transakcjami 

### ISSUE THREAD

**Issue by Ewad20** [JanuaryDecember/Team-Project-PB#17]
Zadanie polega na wprowadzeniu różnych kolorów boxów na stronie z transakcjami w celu odróżnienia przychodów od wydatków. Należy również naprawić wyświetlanie szczegółów transakcji po kliknięciu, umożliwiając ich usuwanie i edycję. Dodatkowo, po dodaniu transakcji przycisk "Cancel" powinien ponownie zmienić się na "Add Transaction".

**Comment by Aikoocioq** [comment]
Aleksandra Didłuch
Aktualizacja strony z transakcjami
![ZmianaKoloruTransakcji1](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/edd6e902-339f-419b-8656-4fb51d694041)
![ZmianaKoloruTransakcji2](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/13be023b-994b-4083-a973-a6645719b478)
Za pomocą krótkiej funkcji, przypisującej transakcji klasę CSS, zależnie od jej typu zmieniono kolory wydatków na wyblakłą czerwień, a przychodów na wyblakłą zieleń.
 
![NieudanaNaprawaPrzycisku](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/0ef4e592-0bc3-46e7-932c-b5e0dd53a3cd)
Mimo prób nie udało się automatycznie przywrócić stanu przycisku „Add Transaction” po dodaniu nowej transakcji. Problem jest spowodowany nieaktualizującą się odpowiednio zmienną useState.
Niepowodzeniem zakończyła się także próba przywrócenia wyświetlania szczegółów transakcji. Okazuje się, że kod nie korzysta w tym celu z podstrony, a z okna dialogowego modal. Aplikacja była w tym miejscu dla mnie niezrozumiała, co uniemożliwiło odnalezienie błędu, powodującego niewyświetlanie okna.
Wniosek: Kwestią szczegółów transakcji i ich wyświetlania musi zająć się osoba, która wyświetlanie w taki sposób napisała.
