### ISSUE TITLE
Poprawa widoczności zdjęcia profilowego oraz responsywności strony głównej

### ISSUE THREAD

**Issue by Ewad20** [JanuaryDecember/Team-Project-PB#18]
Zadaniem jest poprawa błędu związanego z tym, że po dodaniu zdjęcia profilowego jest ono widoczne dopiero po wylogowaniu oraz ponownym zalogowaniu. Dodatkowo, po zalogowaniu imię oraz zdjęcie profilowe na pasku nawigacyjnym powinny pojawiać się od razu,  nie dopiero po odświeżeniu strony. W ramach tego zadania należy również poprawić responsywność strony głównej, aby dostosować jej wygląd i funkcjonalność do różnych urządzeń i rozdzielczości ekranów.

**Comment by kasiagrygo** [comment]
Udoskonaliłam stronę główną, aby była responsywna, dostosowując ją automatycznie do różnych urządzeń, co zapewnia spójne i czytelne doświadczenie użytkownika bez względu na rozmiar ekranu.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/131908455/74f1f956-2626-4a79-ad94-e6ff361d6e13)

Dodałam klasę row oraz dostosowałam style dla odstępów i minimalnej szerokości elementów linku, oraz zmieniłam klasę col-sm-3, co pozwala na lepsze skalowanie szerokości elementów na urządzeniach o różnych rozmiarach ekranów.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/131908455/aec844fd-9b19-4ee0-a7c3-75918f4e3cfc)

Naprawiłam błąd z załadowaniem zdjęcia i imienia, które się aktualizowały dopiero po odświeżeniu strony.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/131908455/913d9e82-02e2-4233-8712-d51453166abc)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/131908455/1fc44dc2-1bdb-4635-86f5-b3f067e91842)
