### ISSUE TITLE
Tłumaczenie strony   

### ISSUE THREAD

**Issue by Ewad20** [JanuaryDecember/Team-Project-PB#19]
Zadanie polega na dodaniu możliwości zmiany języka przez użytkownika systemu.

**Comment by JanuaryDecember** [comment]
**Dokumentacja zadania tłumaczenie strony:**
Moim zadaniem było stworzenie systemu zmiany języka. Nie używałem do tego zewnętrznej biblioteki ponieważ uważałem ją za zbędną.
Oto przetłumaczone fragmenty:
![Screenshot from 2024-05-14 12-27-06](https://github.com/JanuaryDecember/Team-Project-PB/assets/93377326/dbfc124c-2523-48c4-8472-a9ccc8c6a1f8)
![Screenshot from 2024-05-14 12-26-54](https://github.com/JanuaryDecember/Team-Project-PB/assets/93377326/82f2b47a-1def-48f3-bf78-e06c6b656ffc)
Udało mi się to osiągnąć za pomocą pliku json oraz zwykłego importu.
import translation from "../assets/translation.json"
Jest to importowanie tłumaczenia. Tekst jest wklejany w prosty sposób:
{translation[props.language].Dashboard.Receipts}
Tłumacząc na prostszy język, z pliku translations wybieramy język, i z niego wybieramy stronę / komponent, a z niego wybieramy kategorię np tytuł etc.
Udało się zaoszczędzić wagę node_modules przez pominięcie popularnego i18next.
