### ISSUE TITLE
Dodanie kolejnej opcji weryfikacji dwuetapowej

### ISSUE THREAD

**Issue by jdabrowski5701** [JanuaryDecember/Team-Project-PB#2]
Celem zadania jest stworzenie alternatywnej opcji weryfikacji dwuetapowej, np. poprzez kod wysłany na email

**Comment by jdabrowski5701** [comment]
Zadanie wykonane

**Comment by jzaprzalka** [comment]
Proszę o przesłanie dokumentacji

**Comment by Dav0x1** [comment]
**1.Dodanie pól do modelu użytkownika**
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/7ba7e32e-c7ea-44dd-ba52-2b261af031cd)

**2. Dodanie SMTP Credentials do pliku appsettings.json**
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/8439c099-4337-4a73-a90d-c2328ad74e2b)

**3. Konfiguracja usługi do wysyłania wiadomości e-mail do konkretnych użytkowników (Services/EmailSender.cs)**
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/f0f1453b-8d7d-4905-a33b-6e883f5f3f75)

**4. Dodanie kontrolerów API**
Dezaktywacja autentykacji przez e-mail
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/1e128bc7-e680-4779-a28d-b2b6cbdbc188)

Aktywacja autentykacji przez e-mail
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/101e814e-00df-4aef-9893-9dec8809c781)

Pobranie statusu autentykacji przez e-mail
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/6c53497b-2da1-40a2-8a91-e4f51ce3059c)

Wysłanie wiadomości e-mail z kodem do autentykacji
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/b6a07654-866d-4177-b11a-f7855694e525)

5.Dodanie walidacji weryfikacji dwuetapowej do kontrolera logowania
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/05402a7c-cd8f-4539-bb4e-b6c10bf18acd)

6.Dodanie aktywacji oraz dezaktywacji do widok SPA
https://github.com/JanuaryDecember/Team-Project-PB/commit/7c47b808b51341ec5db8ed339d831f713d715808#diff-53b11aa48cf0e861f8c99415ee21ccb1c34b47db19f00b47d8c82ee9587fdeb2

7.Dodanie formularza do widoku logowania z autentykacją przez e-mail
https://github.com/JanuaryDecember/Team-Project-PB/commit/78d712eb635ae5fc0e58c337c79d2029187b8ae3#diff-adf25c071a0263311b8702befc83d053d4d36b6955139c2f279f628a527e2802

8. Wizualizacja
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/818fda6f-68f8-495c-87c6-d7618e35ad96)
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/a7c4c6f6-7dd1-47e0-92b0-3746a82fcb3f)
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/2e147b9a-892b-4992-9a02-66efb30fba56)
