### ISSUE TITLE
Rozbudowa funkcjonalności budżetu

### ISSUE THREAD

**Issue by Ewad20** [JanuaryDecember/Team-Project-PB#20]
Zadanie polega na dodaniu w budżecie przycisku "SZCZEGÓŁY", który umożliwia użytkownikowi zobaczenie listy transakcji powiązanych z danym budżetem, wraz z datą dodania oraz kwotą. Ewentualnie, po kliknięciu w dany budżet, może otwierać się okno ze szczegółami, zawierające także przeniesione przyciski edytowania oraz usuwania budżetu.

**Comment by emek-k** [comment]
Frontend
<img width="452" alt="image" src="https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/4d3f105a-c6c3-423b-82b1-dcf81fff5d8d">
<img width="452" alt="image" src="https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/2d6d67dc-2047-4978-a0f3-f6a8705b084a">
Dodanie loadBudgetTranations do zaladowania transakcji dla danego portfela, ktore podlegaja danemu budzetowi.
<img width="394" alt="image" src="https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/b6602bca-645a-4eb9-a8f1-3dd574ca414f">
Obsluga przycisku ‘details’
<img width="328" alt="image" src="https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/18b7506b-1790-47d7-9d5b-a9d3957ba168">
Obsluga przycisku ‘x’ (wyjscie) z ‘details’
<img width="452" alt="image" src="https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/9042b5c1-51cf-4b5b-88e9-a199acd7d1da">
Przekierowanie do strony transakcji danego portfela podpiętego pod dany budżet.
<img width="452" alt="image" src="https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/267d9656-cae2-453b-990e-f0316ff5d842">
Backend
<img width="452" alt="image" src="https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/01486db4-1a72-4399-ae81-708273b494a2">
Dodanie nowego kontrolera, który zwraca listę transakcji dla danego budżetu.
<img width="452" alt="image" src="https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/6724be03-5dad-41dc-8785-fd669b06eeaa">
<img width="452" alt="image" src="https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/0105bf4f-ebab-4a03-9f5f-ba71e8243832">
<img width="452" alt="image" src="https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/9b97c456-b8fe-4635-ac98-9b3764fa7503">
<img width="452" alt="image" src="https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/ecf4a47d-503d-4984-a088-a396376da5ae">
