### ISSUE TITLE
Wyświetlanie zdjęć paragonów  

### ISSUE THREAD

**Issue by Ewad20** [JanuaryDecember/Team-Project-PB#21]
Zadaniem jest umożliwienie użytkownikowi wyświetlania zjęć paragonów poprzez bezpośrednie przejście do nich za pomocą linku do dysku Google lub poprzez przeglądanie ich bezpośrednio w aplikacji. Ponadto, należy dodać przekierowanie do tej funkcji do boksu "My Receipt" na stronie głównej.

**Comment by czyzia2002** [comment]
**Dodanie przekierowania z boksu "My Receipt" na stronie głównej do odpowiedniej strony.**
 
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/09cfbedb-cedb-4e55-8a86-f6b6f819f8c8)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/24db5468-5cb9-47b9-ada8-637ec85e2789)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/708f6830-dd7b-4f28-a6e8-3ca8d179fb5b)

**Generowanie linku do folderu użytkownika.**
Zmieniono sposób łączenia się z API oraz dodano dodatkowy klucz uwierzytelniający, który służy jedynie do przeglądania zawartości folderu. Odpowiedni klucz wywoływany jest w funkcji.

Łączenie się z API.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/60160682-07b9-4162-9980-16a39ded2b77)
 
Pobieranie linku do folderu użytkownika.
 
 
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/5e868fbb-246b-4b56-a5bc-947c54e64f90)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/cac4f606-5b52-4a25-8407-739f6e3fccb9)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/439a7274-d0d0-4cb0-abec-f4ee95fd23c4)

**Pobieranie i wyświetlanie zdjęć z dysku Google na stronie aplikacji.**
 
 
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/d8085635-1a18-437e-8d2e-7d42208ec42a)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/1761795b-a8ef-4013-a69f-e9092d339a55)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/dfe85702-bb49-4960-9f1d-3abfae0a420f)

Wyświetlanie zdjęć jest odświeżana za każdym razem, gdy zostanie dodane nowe zdjęcie.

**Podgląd aplikacji.**
 
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/38e9449b-1170-4681-8cb8-41f3753b2edd)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/09598756-3b48-4079-89b0-0e00c11d1fbf)
