### ISSUE TITLE
Poprawa weryfikacji dwuetapowej 

### ISSUE THREAD

**Issue by Ewad20** [JanuaryDecember/Team-Project-PB#22]
Zadanie polega na tym, że po aktywowaniu weryfikacji za pomocą e-maila lub pytania pomocniczego, status TwoFactorEnabled ma być ustawiany na "Yes". Dodatkowo, po skonfigurowaniu opcji  weryfikacji za pomocą pytania pomocniczego, należy uwzględnić je podczas procesu logowania.

**Comment by Dav0x1** [comment]
**1.Wizualizacja**
Zaktualizowano informację o statusie aktywacji weryfikacji dwuetapowej
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/9dad72d5-24e9-4c6e-b26e-7e2621b61e0b)
Dodano weryfikację za pomocą pytania pomocniczego przy logowaniu
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/534569aa-6122-4f15-9a92-3d65f6ba80f2)
**2.Zmiany w kodzie**
-Dodano walidację logowania dwuetapowego po przez pytanie pomocnicze w kontrolerze Account dla metody Login
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/578f5329-0c0d-45fb-af90-f29867dd7fb6)
https://github.com/JanuaryDecember/Team-Project-PB/commit/5a7f5e33653b1f24b359402c7eb828a66224c3dc#diff-27463f7bb252b168514c3778246bb5173cf71518b0992eccda47d92e25c1191a
-Zaktualizowano wyświetlanie statusu weryfikacji dwuetapowego po stronie frontendu dla ProfilePage.jsx
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/d6b6b4f8-9b61-4c5e-ac33-763b0e3080c4)
https://github.com/JanuaryDecember/Team-Project-PB/commit/5a7f5e33653b1f24b359402c7eb828a66224c3dc#diff-8e10c8bed0f0ffed4bd8213e3375f75dd94a84a26aae49523443291130124111
-Do formularza z logowanie dodano możliwość wpisania pytania z weryfikacji dwuetapowej, jeżeli jest wymagane
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/dc000475-1381-48a8-b680-255fde3132d8)
https://github.com/JanuaryDecember/Team-Project-PB/commit/5a7f5e33653b1f24b359402c7eb828a66224c3dc#diff-adf25c071a0263311b8702befc83d053d4d36b6955139c2f279f628a527e2802
