### ISSUE TITLE
Usprawnienie procesu dodawania transakcji

### ISSUE THREAD

**Issue by Ewad20** [JanuaryDecember/Team-Project-PB#23]
Zadaniem jest dodanie powiadomienia w przypadku niepowodzenia wczytywania kwoty ze zdjęcia paragonu. Pole umożliwiające dodanie zdjęcia ma zostać przeniesione na górę formularza dodawania transakcji. Dodatkowo, należy dodać pasek postępu, informujący o etapie procesu odczytywania kwoty.

**Comment by jdabrowski5701** [comment]
Przeniesienie pola dodawania zdjęcia na górę formularza oraz dodanie paska informującego użytkownika że trwa dekodowanie danych z paragonu.
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/e1c9b55a-4bdd-4516-81a9-2fe1adf96e35)

Usprawniono powiadomienie że zakończono dekodowanie.
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/fec1dff2-7a5b-49fd-bad6-b1e57bc59ab6)

Dodanie powiadomienia w przypadku niepowodzenia wczytywania kwoty ze zdjęcia paragonu
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/6aaa66fa-1a82-4832-8e64-97682c8d16dd)
