### ISSUE TITLE
Dokończenie tłumaczenia strony

### ISSUE THREAD

**Issue by kasiagrygo** [JanuaryDecember/Team-Project-PB#25]
Dokończenie tłumaczenia strony z angielskiego na polski.

**Comment by jdabrowski5701** [comment]
Celem zadania było wykorzystanie istniejącego systemu wyboru języka i dodanie brakującego tłumaczenia dla poszczególnych stron. Zadanie zostało wykonane. Poniżej przykłady przetłumaczonych stron na język polski:

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/309dabbb-9104-446e-8372-b8c28e5f76d5)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/76966879-4817-4079-9fda-a233ee99fca8)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/6b7ce267-f590-4ffd-9d3f-b87a7b52e924)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/9ca8e03b-fd52-481b-9c88-1e1ee381ea5f)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/d8d5dff3-a463-4aaf-baff-1978d193a3be)
