### ISSUE TITLE
Dodanie historii spłat obligacji

### ISSUE THREAD

**Issue by kasiagrygo** [JanuaryDecember/Team-Project-PB#26]
Zadaniem jest dodanie do każdej obligacji listy spłat z kwotą i datą spłaty.

**Comment by Ewad20** [comment]
Dodano trzy stany do komponentu za pomocą hooka _useState_. Pierwszy, _showRepaymentsModal_, reprezentuje stan określający, czy modal związany z spłatami jest widoczny (początkowo ustawiona na wartość _false_). Drugi stan, _selectedObligationRepayments_, to tablica przechowująca wybrane spłaty zobowiązań. Początkowo jest to pusta tablica. Trzeci stan, _selectedObligationDetails_, przechowuje szczegóły wybranego zobowiązania. Na początku jest to pusty obiekt.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/119815824/8068ed9e-8c4e-4b3a-bafb-fbe39bf99214)

Funkcja _fetchRepayments_ pobiera spłaty i szczegóły zobowiązania dla określonego identyfikatora. Jeśli pobranie się powiedzie, ustawia odpowiednie stany i otwiera modal. W przypadku niepowodzenia, wyświetla alert. Funkcja _handleCloseRepaymentsModal_ odpowiada natomiast za zamknięcie modala.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/119815824/601befbf-74d4-42e2-b670-eb914e0b1829)

Zaimplementowano modal, który wyświetla szczegóły zobowiązania oraz jego spłaty. Jest wyświetlany lub ukrywany w zależności od stanu _showRepaymentsModal_. Szczegóły zobowiązania i spłaty są pobierane przy użyciu funkcji _fetchRepayments_ i przechowywane w odpowiednich stanach.  W sekcji _modal-body_ znajdują się szczegóły zobowiązania, takie jak nazwa, kwota, kategoria, opis, data rozpoczęcia i termin płatności. Dodatkowo wyświetlane są spłaty zobowiązania w formie listy. 

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/119815824/7bb341a8-3497-4038-bf5b-efe8d5424595)

Akcja _GetRepayments_ została zaimplementowana jako metoda HTTP GET, która przyjmuje parametr _obligationId_. W tej akcji zwracana jest lista spłat zobowiązania o określonym identyfikatorze. Dane te są pobierane z bazy danych. Następnie lista spłat jest przekazywana jako odpowiedź HTTP.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/119815824/705256ad-4772-4cbd-b484-2e23d94a98b3)

Poniższa akcja kontrolera obsługuje żądania GET i wymaga, aby użytkownik był uwierzytelniony. Następnie pobiera szczegóły zobowiązania o określonym identyfikatorze. Jeśli użytkownik nie jest zalogowany lub zobowiązanie nie istnieje, zwracane są odpowiednie komunikaty błędu. W przeciwnym razie zwracane są szczegóły zobowiązania w formie obiektu DTO.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/119815824/5539beb4-011b-4f4d-a109-8a93814a4d66)

Wygląd na stronie:

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/119815824/91b35ef8-d6e0-4f6b-8dbd-a93392f1139f)
