### ISSUE TITLE
Naprawa zmiany typu kategorii

### ISSUE THREAD

**Issue by kasiagrygo** [JanuaryDecember/Team-Project-PB#27]
W przypadku zmiany typu kategorii w zakładce kategorie w transakcjach pozostaje stara kategoria.

**Comment by Dav0x1** [comment]
**Rozwiązanie problemu**
W przypadku zmiany typu kategorii na przeciwną, kategoria jest usuwana z transakcji(przychodów lub rozchodów) do których była przypisana. 

**1. Zmiana w modelu Transakcji**
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/73373573-6236-4cfd-adab-093c2393e804)
**2. Edycja kontrolera edycji kategorii**
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/d71a02df-155e-4c50-a4b0-2bd765a8c10f)
**3. Wizualizacja**
Transakcje z testowa kategorią przypisaną do przychodu
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/e5a9e173-86d0-40c2-b915-12022b890e8f)
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/9bbda137-5f14-4111-90bd-6abbb7268bdd)
Zmiana typu kategorii
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/086cde99-1166-49b1-9970-c08df0390fae)
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/a5fe738b-c943-43e0-8f0c-14fe79d2667c)
