### ISSUE TITLE
Poprawki w transakcjach i dodawaniu zdjęcia.

### ISSUE THREAD

**Issue by kasiagrygo** [JanuaryDecember/Team-Project-PB#28]
Po dodaniu transakcji nie zmienia się przycisk z powrotem na dodanie transakcji. Przy dodaniu zdjęcia profilowego pojawia się one dopiero po ponownym zalogowaniu.

**Comment by czyzia2002** [comment]
**Poprawa dodawania transakcji** – po pomyślnym dodaniu transakcji przycisk ‘Cancle’ powinien zmienić się automatycznie na ‘Add Transaction’ oraz opcje rodzaju transakcji powinny zniknąć.

W pliku TransactionForm w funkcji handleSubmit dodano odwołanie do funkcji onCancle, która wywoływana jest po zatwierdzeniu dodania transakcji ( w pliku TransactionPage)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/20c5441f-e678-4c84-83ce-84e62058dee4)

Fragment wywołania onCancle:

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/7660b028-912c-42a9-8700-11c4110d4897)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/31557572-9b82-4026-b159-8231e7c16404)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/8783a418-c154-4a3f-afea-ac78d37f1a2c)


Poprawy wyświetlania zdjęcia profilowego nie udało się zrealizować.
