### ISSUE TITLE
Walidacja dodawania obligacji 

### ISSUE THREAD

**Issue by kasiagrygo** [JanuaryDecember/Team-Project-PB#29]
Walidacja input boxów w tworzeniu/edycji obligacji oraz dodanie odstępu po Delete.

**Comment by Aikoocioq** [comment]
Aleksandra Didłuch
Walidacja dodawania obligacji

![WalidacjaDodawaniaObligacji](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/374315f7-9648-4563-aa09-8a1d59b99210)
![WalidacjaDodawaniaObligacjiKod](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/bf0a9467-5cef-4c29-a0de-9c62079d8356)
Wprowadzono walidację przy dodawaniu nowych obligacji. Niektóre elementy były już automatycznie weryfikowane opcją „required”, dlatego dodano kolejne wymogi:
- Kategoria obligacji musi zostać wybrana
- Tytuł musi zawierać przynajmniej 3 znaki
- Kwota obligacji musi być większa od 0
- Data rozpoczęcia musi być przed datą zakończenia
- Typ płatności musi zostać wybrany 
 
![WalidacjaEdytowaniaObligacji](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/cfa1d71c-307a-441b-933f-b01d209eb008)
![WalidacjaEdytowaniaObligacjiKod](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/05072478-90e3-4ee9-85b5-35fd681bdc90)
W podobny sposób dodano również walidację przy edycji obligacji. Sprawdzane warunki to:
- Tytuł musi zawierać przynajmniej 3 znaki
- Kwota obligacji musi być większa od 0
- Data rozpoczęcia musi być przed datą zakończenia
Dodatkowo naprawiono sposób wyświetlania dat, bowiem przy przejściu do edycji obie daty wyświetlały się jako dd.mm.rrrr.
 
![OdstępPoDelete](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/cf7138d8-0212-4173-8825-60cad5e5280a)
Przy użyciu marginesu dodano przerwę po przycisku „Delete”, by nie stykał się on z krawędzią ramki.
