### ISSUE TITLE
Dodanie wykresu na stronie transakcji

### ISSUE THREAD

**Issue by jdabrowski5701** [JanuaryDecember/Team-Project-PB#3]
Celem zadania jest dodanie wykresu na stronie transakcji portfela, aby użytkownik miał lepszy wgląd do stosunku przychodów i rozchodów

**Comment by jdabrowski5701** [comment]
Zadanie wykonane

**Comment by jzaprzalka** [comment]
Wykonane. Proszę o przesłanie dokumentacji

**Comment by Ewad20** [comment]
[Dokumentacja.pdf](https://github.com/JanuaryDecember/Team-Project-PB/files/15093327/Dokumentacja.pdf)

**Comment by jzaprzalka** [comment]
Graded: 5
