### ISSUE TITLE
Walidacja budżetu

### ISSUE THREAD

**Issue by kasiagrygo** [JanuaryDecember/Team-Project-PB#30]
Dodanie dodatkowej walidacji przy dodawaniu nowego budżetu.

**Comment by emek-k** [comment]
FRONTEND BEFORE
![budget-before](https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/75504008-3695-4418-8956-a7a359668372)
FRONTEND AFTER
![budget-after](https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/be910722-efae-4b8c-97e0-d4db4c675bf3)
<img width="489" alt="image" src="https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/b116199f-fccc-446b-a490-bba1dc2abecf">
<img width="894" alt="image" src="https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/2aca8d16-9f05-4ef3-9559-567e3765a0ba">

BACKEND
<img width="981" alt="image" src="https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/d94b752f-1b0e-4812-a6ba-1323035d653c">
