### ISSUE TITLE
Rozbicie kontrolerów na serwisy i kontrolery

### ISSUE THREAD

**Issue by kasiagrygo** [JanuaryDecember/Team-Project-PB#31]
Usuwamy bezpośrednie odwołania do bazy danych z kontrolerów, zamiast tego tworzymy serwisy do dostępu do danych.

**Comment by JanuaryDecember** [comment]
**Dokumentacja zadania Rozbicie kontrolerów na serwisy i kontrolery**
Moje zadanie polega na refaktoryzacji kodu, w celu zbliżenia go do stylu SOLID. Aktualnie cała logika dotycząca naszego programu była w kontrolerach oraz nie uporządkowana. Przykładowo, logika zawarta w ponad tysiąc linijkowym pliku AccountController, została rozbita na sześć (!) serwisów oraz kontrolerów:
Wallet,
Authentication,
GoogleAuth,
EmailAuth,
QuestionAuth,
User.
Zostały również użyte niestandardowe wyjątki, dzięki czemu kod jest przejrzysty, oraz poprawiona w ten sposób została obsługa błędów.
Zmiany nie zostały zmergowane, ponieważ to zadanie na kilka sprintów, jeszcze nie zostało skończone.
![Screenshot from 2024-05-22 11-17-08](https://github.com/JanuaryDecember/Team-Project-PB/assets/93377326/86235b18-c4a2-42cd-b103-ac074db183e2)
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/93377326/80f6e2b2-b812-4233-8047-93331064effe)
