### ISSUE TITLE
Wykres obligacji

### ISSUE THREAD

**Issue by czyzia2002** [JanuaryDecember/Team-Project-PB#33]
Wykres pokazujący/porównujący sumę wszystkich obligacji do sumy dotychczasowych spłat.

**Comment by Ewad20** [comment]
Dodano komponent _ObligationsChart,_ który jest używany do wyświetlenia wykresu kołowego reprezentującego podsumowanie zobowiązań finansowych. Komponent ten wykorzystuje bibliotekę _Chart.js do_ generowania wykresu na podstawie przekazanych danych.
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/119815824/d8964aec-9672-40a0-a497-df13e20be2cb)

Użyto hooka _useEffect_, który monitoruje zmiany w tablicy _obligations_. Jeśli zawiera ona co najmniej jeden element, stan _chartReady_ zostaje ustawiony na _true_, co sygnalizuje gotowość do wyświetlenia wykresu.
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/119815824/4324d248-82ce-4683-bb64-1be06f947646)

Dodano fragment, który oblicza sumę wszystkich spłaconych kwot z zobowiązań oraz sumę wszystkich zobowiązań. Pierwsza linia sumuje spłacone kwoty za każde zobowiązanie, a druga - same kwoty zobowiązań.
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/119815824/e94ace11-ab74-4674-b71e-a84272f77989)

Zaimplementowano warunek sprawdzający, czy zmienna _chartReady_ jest ustawiona na _true_. Jeśli tak, to renderowany jest komponent _ObligationsChart_, z przekazaniem właściwości _totalRepaid_ i _totalObligation_.
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/119815824/4fa9786c-87a3-4687-ba39-0adfc2c8cacc)

Wygląd wykresu na stronie:
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/119815824/5f3d1414-ad75-429c-a913-4944bdab8ab5)
