### ISSUE TITLE
Kontynuacja - Rozbicie kontrolerów na serwisy i kontrolery 

### ISSUE THREAD

**Issue by czyzia2002** [JanuaryDecember/Team-Project-PB#34]
Usunięcie bezpośrednich odwołań do bazy danych z kontrolerów, zamiast tego utworzenie serwisu do dostępu do danych.

**Comment by JanuaryDecember** [comment]
**Dokumentacja kontynuacji zadania**
W tym sprincie zająłem się kontynuacją rozbijania kontrolerów na serwisy oraz kontrolery. Tym razem zacząłem dodawać DTO's aby poprawić bezpieczeństwo oraz możliwie przyspieszyć przesył danych. Zacząłem również poprawiać i dostosowywać modele do standardów języka oraz dalej poprawiać kontrolery.
Niestety, nasza aplikacja ma zbyt duży dług techniczny, aby refaktoryzować kod, przy równoczesnym dodawaniu nowych funkcjonalności. Moją opinią jest zaprzestanie dodawania funkcjonalności oraz skupienie się na refaktoryzacji, lub zaniechanie jej.
