### ISSUE TITLE
Tłumaczenie strony

### ISSUE THREAD

**Issue by czyzia2002** [JanuaryDecember/Team-Project-PB#35]
Tłumaczenie strony z języka angielskiego na język polski.

**Comment by jdabrowski5701** [comment]
Dodano tłumaczenie wykresów występujących na poszczególnych stronach, uzupełniono tłumaczenie strony BudgetPage oraz poprawiono błędy i brakujące tłumaczenia.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/96dd9f34-dfed-4a22-9ddc-26d06f89cadb)
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/e6d27463-9f56-4812-a356-dd353efac16e)
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/7ac68e6d-1c79-438c-b6d2-196662e35d83)
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/6bfb3723-04c9-4265-9369-138aec505594)
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/4fb36e0f-c5ab-4fe1-abf0-ce6503d489f3)
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/33179415/59488f9e-b335-4181-a58a-14c74991bab8)
