### ISSUE TITLE
Poprawa edycji i usuwania zobowiązania

### ISSUE THREAD

**Issue by czyzia2002** [JanuaryDecember/Team-Project-PB#36]
Dodanie możliwości rezygnacji z edycji zobowiązania. I dodanie komunikatu/potwierdzenia, że na pewno chce się usunąć zobowiązanie.

**Comment by Aikoocioq** [comment]
Aleksandra Didłuch
Poprawa edycji i usuwania zobowiązania
![1](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/04acad46-b98b-4576-8c0c-1799bae61c67)
![2](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/cab1d2fc-1a8d-49d9-baaf-fb89bc87fea4)
Dodano zmianę stanu przycisku "Add Obligation" na "Cancel" w przypadku dodawania obligacji.
 
![3](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/b7b6c76b-8992-455b-9604-4123abb78451)
![4](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/204ab060-fa46-46c3-82e9-4b1cef0fbf07)
Dodano przyciski "Cancel" przy spłacaniu i edycji obligacji.

![5](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/346b74cf-56f7-4359-84a4-6f794013b017)
Dodano komunikat, wymagający potwierdzenia chęci usunięcia wybranej obligacji.

Dla wszystkich dodanych elementów utworzone od razu zostały ich tłumaczenia, a dodatkowo poprawiono na stronie miejsca, w których tłumaczeń zabrałko.
