### ISSUE TITLE
Walidacja dodawania i edytowania transakcji

### ISSUE THREAD

**Issue by czyzia2002** [JanuaryDecember/Team-Project-PB#37]
Dodanie dodatkowej walidacji do dodawania oraz edycji transakcji

**Comment by kasiagrygo** [comment]
Dodałam warunki walidacyjne które, sprawdzają czy wszystkie pola formularza są wypełnione oraz czy wartości wprowadzone przez użytkownika spełniają określone kryteria, takie jak minimalna i maksymalna długość dla tytułu i opisu, oraz czy kwota jest dodatnia liczba. Jeśli którykolwiek z warunków nie jest spełniony, wyświetlany jest odpowiedni komunikat błędu, informujący użytkownika o wymaganiach dotyczących poszczególnych pól formularza.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/131908455/496b9b34-024c-4b47-8000-68d31fe61096)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/131908455/4b0b5b86-a1b4-4f2a-b973-0d0452fd924e)

W przypadku dodawania transakcji na dole wyświetla się komunikat z błędem. 

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/131908455/2df0dc88-b49b-4c77-8994-067d0b570d20)

W przypadku edycji danych mamy powiadomienie, które pojawia się na chwilę i informuje o błędzie.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/131908455/9bc6d601-341f-40c1-b8b7-7fd26beb13e7)
