### ISSUE TITLE
Postawienie aplikacji na Docker

### ISSUE THREAD

**Issue by czyzia2002** [JanuaryDecember/Team-Project-PB#38]
Uruchomienie aplikacji w kontenerze Docker, co umożliwi łatwiejsze zarządzanie zależnościami oraz wdrożenie na różnych środowiskach.

**Comment by Dav0x1** [comment]
**Zrealizowane zmiany**

1. Stworzeniu pliku Dockerfile
- Buildowanie API oraz SPA
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/d8cdedc7-8343-4e52-b1e3-ad6681b2ee27)
2. Stworzenie pliku docker-compose.yml
- Utworzenie obrazu bazy danych mssql oraz zapewnienie odpowiedni zmienny środowiskowych dla konfiguracji API w celu połączenia się z bazą danych
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/0de4a67b-5db6-4094-8d66-3528ca52b47f)
3. Utworzenie serwisu DatabaseManagmentService.cs
- Realizacja funkcji automatyzującej tworzenie migracji przy inicjalizacji
- Dodanie funkcji umożliwiające pobranie podstawowego connection stringa lub podanego w zmienny środowiskowych
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/f3f46991-25e9-4a0b-b754-715a7036bcb2)
4. Zaktualizowanie Program.cs wykorzystując zaimplementowane metody w DatabaseManagmentService.cs
![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/159195917/c86865c9-b63a-41c5-925c-69adf79622ec)
