### ISSUE TITLE
Dodanie odwołania do strony z budżetami

### ISSUE THREAD

**Issue by czyzia2002** [JanuaryDecember/Team-Project-PB#39]
Dodanie odwołania do strony z budżetami, aby można było z poziomu strony głównej przejść do strony z budżetami.

**Comment by emek-k** [comment]
Zrobione https://github.com/JanuaryDecember/Team-Project-PB/commit/7145b5b46dc11ef9afa8e0c2350195132373db1b
<img width="1260" alt="image" src="https://github.com/JanuaryDecember/Team-Project-PB/assets/48961771/876a1b70-b7bf-4292-8c59-4e0381fcb37f">
