### ISSUE TITLE
Dodawanie paragonów za pomocą formularza (Frontend)

### ISSUE THREAD

**Issue by jdabrowski5701** [JanuaryDecember/Team-Project-PB#4]
Celem zadania jest stworzenie strony z formularzem, na której użytkownik będzie mógł dodać paragon

**Comment by jdabrowski5701** [comment]
Zadanie wykonane

**Comment by jzaprzalka** [comment]
Wykonene. Proszę o przesłanie dokumentacji

**Comment by Aikoocioq** [comment]
**Aleksandra Didłuch
Dodawanie paragonu za pomocą formularza - frontend**

- Zmieniono układ strony, załączając w niej formularz, który oprócz wyboru grafiki i jej podglądu zawiera również pole do wprowadzenia nazwy pliku.

![FormularzDodawaniaParagonu](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/529aeeff-75e3-448a-8d26-3c952227679f)

- Wprowadzenie nazwy dla grafiki jest konieczne, o czym informuje komunikat wyświetlający się podczas próby zapisania paragonu bez podania tejże nazwy.

![FormularzDodawaniaParagonu2](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/94d94517-eeb8-4df8-8044-e73072ff165e)

- Wymagane jest też wybranie zdjęcia, a niezrobienie tego lub wybranie pliku, niebędącego grafiką skutkuje odpowiednim komunikatem.

![FormularzDodawaniaParagonu4](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/a575343a-5399-4ef4-b231-3735cdb464d6)
![FormularzDodawaniaParagonu3](https://github.com/JanuaryDecember/Team-Project-PB/assets/106675277/c2eb34e4-9a80-4b76-84e6-d517a9c351c4)

**Comment by jzaprzalka** [comment]
Ocenione: 5
