### ISSUE TITLE
Dodanie opcji edycji budżetu

### ISSUE THREAD

**Issue by jdabrowski5701** [JanuaryDecember/Team-Project-PB#5]
Celem zadania jest dodanie możliwości edycji istniejącego budżetu

**Comment by jdabrowski5701** [comment]
Zadanie wykonane

**Comment by jzaprzalka** [comment]
Wykonane. Proszę o przesłanie dokumentacji

**Comment by emek-k** [comment]
Dokumentacja zadania.
[Uploading PZTRAC-?? - Dodanie edycji i usuwania budzetu.pdf…]()
