### ISSUE TITLE
Dodawanie zdjęcia paragonów

### ISSUE THREAD

**Issue by jdabrowski5701** [JanuaryDecember/Team-Project-PB#6]
Celem zadania jest stworzenie funkcjonalności pozwalającej użytkownikowi dodać zdjęcie paragonu.

**Comment by jdabrowski5701** [comment]
Zadanie wykonane

**Comment by jzaprzalka** [comment]
Wykonane. Proszę o przesłanie dokumentacji

**Comment by czyzia2002** [comment]
Pola statyczne wykorzystywane do uwierzytelniania API Google Drive.

<img width="389" alt="Pola statyczne" src="https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/ecaf1344-47f6-4e9b-9b87-ec1352659a28">

Funkcja Upload:
Sprawdzenie czy przesłano plik z frontend’u oraz tworzenie połączenia z API.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/6336796b-e1ce-4e5a-8fcc-0f8ab4451b79)

Tworzenie metadanych pliku Google i ustawianie nazwy, która przekazywana jest z frontend’u (użytkownik nadaje nową nazwę) oraz metoda przesyłania pliku.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/768dd6f5-1f9b-4ec7-908a-716b369002f9)

Przykładowe dodawanie zdjęcia paragonu:

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/51db7176-4093-4c7c-9bdf-434698d6bbec)

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/13e34c4c-e38e-4f9a-8248-dede487a909b)

Zawartość Google Drive po przesłaniu pliku.

![image](https://github.com/JanuaryDecember/Team-Project-PB/assets/127155100/f1ba5b23-d6b4-4550-bb4d-5d2a420d6cdd)

**Comment by jzaprzalka** [comment]
Graded: 5
