### ISSUE TITLE
Opcja dodania zdjęcia profilowego użytkownika

### ISSUE THREAD

**Issue by jdabrowski5701** [JanuaryDecember/Team-Project-PB#7]
Celem zadania jest rozszerzenie możliwości personalizacji profilu użytkownika o opcję dodania zdjęcia profilowego

**Comment by jdabrowski5701** [comment]
Zadanie wykonane

**Comment by jzaprzalka** [comment]
Wykonane. Proszę o przesłanie dokumentacji

**Comment by kasiagrygo** [comment]
[Dokumentacja.pdf](https://github.com/JanuaryDecember/Team-Project-PB/files/15093363/Dokumentacja.pdf)

**Comment by jzaprzalka** [comment]
Ocenione: 5
