### ISSUE TITLE
Wprowadzenie powiadomień dotyczących budżetów

### ISSUE THREAD

**Issue by Aikoocioq** [JanuaryDecember/Team-Project-PB#8]
Zadanie polega na dodaniu funkcji powiadomień, które będą informowały użytkownika o np. przekroczeniu budżetu.

**Comment by emek-k** [comment]
[EK-sprint-13-dokumentacja.pdf](https://github.com/JanuaryDecember/Team-Project-PB/files/15225001/EK-sprint-13-dokumentacja.pdf)
